export const communityCards = [
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'La vente de votre stock vous rapporte 50€.',
        resume: 'Vous avez gagné 50€.',
        effect: {type: 'money', data: 50},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Recevez votre revenu annuel 100€.',
        resume: 'Vous avez gagné 200€.',
        effect: {type: 'money', data: 200},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Payez la note du Medecin 50€.',
        resume: 'Vous avez perdu 50€.',
        effect: {type: 'money', data: -50},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Vous avez gagné le deuxième Prix de Beauté. Recevez 100€.',
        resume: 'Vous avez gagné 100€.',
        effect: {type: 'money', data: 100},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Retournez à Belleville.',
        resume: 'Vous vous êtes déplacé jusqu\'à Bouldevard de Belleville',
        effect: {type: 'teleportation', data: 2},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Vous êtes libéré de prison. Cette carte peut être conservée jusqu\'à ce qu\'elle soit utilisée ou vendue.',
        resume: 'Vous avez reçu la carte "Libéré de prison".',
        effect: () => {} // Some codes here
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Placez vous sur le case "Départ".',
        resume: 'Vous vous êtes déplacé jusqu\'à la case Départ',
        effect: {type: 'teleportation', data: 1},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Vous héritez 100€.',
        resume: 'Vous avez gagné 100€.',
        effect: {type: 'money', data: 100},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Payer une amende de 10€ ou bien tirez une carte "CHANCE"',
        resume: {}, //some text here,
        effect: () => {} // some codes here;,
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Recevez votre intérêt sur l\'emprunt à 7%. 25€.',
        resume: 'Vous avez gagné 25€.',
        effect: {type: 'money', data: 25},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'C\'est votre anniversaire: chaque joureur doit vous donner 10€.',
        resume: 'Tous les autres joueurs vous ont donné 10€.',
        effect: {}, // some codes here;,
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Payer à l\'Hôpital 100€.',
        resume: 'Vous avez perdu 100€.',
        effect: {type: 'money', data: -100},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Payer votre Police d\'Assurance s\'élevant à 50€.',
        resume: 'Vous avez perdu 50€.',
        effect: {type: 'money', data: -50},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Erreur de la Banque en votre faveur. Recevez 200€.',
        resume: 'Vous avez gagné 200€.',
        effect: {type: 'money', data: 200},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Les Contributions vous remboursent la somme de 20€.',
        resume: 'Vous avez gagné 20€.',
        effect: {type: 'money', data: 20},
    },
    {
        type: 'community',
        name: 'Caisse de commnauté',
        message: 'Allez en prison. Rendez vous directement à la prison. Ne franchissez pas la case "Départ". Ne touchez pas 200€.',
        resume: 'Vous vous êtes téléporté jusqu\'à la case Prison',
        effect: {type: 'teleportation', data: 11},
    }
];
